//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatelliteLinkCalculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double UplinkFrequency {
            get {
                return ((double)(this["UplinkFrequency"]));
            }
            set {
                this["UplinkFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkAntennaDiameter {
            get {
                return ((double)(this["UplinkAntennaDiameter"]));
            }
            set {
                this["UplinkAntennaDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkAntennaEfficiency {
            get {
                return ((double)(this["UplinkAntennaEfficiency"]));
            }
            set {
                this["UplinkAntennaEfficiency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkTransmitGain {
            get {
                return ((double)(this["UplinkTransmitGain"]));
            }
            set {
                this["UplinkTransmitGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkPowerAtFeed {
            get {
                return ((double)(this["UplinkPowerAtFeed"]));
            }
            set {
                this["UplinkPowerAtFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkEIRP {
            get {
                return ((double)(this["UplinkEIRP"]));
            }
            set {
                this["UplinkEIRP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkRange {
            get {
                return ((double)(this["UplinkRange"]));
            }
            set {
                this["UplinkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkPathLoss {
            get {
                return ((double)(this["UplinkPathLoss"]));
            }
            set {
                this["UplinkPathLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkPFD {
            get {
                return ((double)(this["UplinkPFD"]));
            }
            set {
                this["UplinkPFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkNoiseBandwidth {
            get {
                return ((double)(this["UplinkNoiseBandwidth"]));
            }
            set {
                this["UplinkNoiseBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkGT {
            get {
                return ((double)(this["UplinkGT"]));
            }
            set {
                this["UplinkGT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkCN {
            get {
                return ((double)(this["UplinkCN"]));
            }
            set {
                this["UplinkCN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkFrequency {
            get {
                return ((double)(this["DownlinkFrequency"]));
            }
            set {
                this["DownlinkFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkAntennaDiameter {
            get {
                return ((double)(this["DownlinkAntennaDiameter"]));
            }
            set {
                this["DownlinkAntennaDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkAntennaEfficiency {
            get {
                return ((double)(this["DownlinkAntennaEfficiency"]));
            }
            set {
                this["DownlinkAntennaEfficiency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkReceiveGain {
            get {
                return ((double)(this["DownlinkReceiveGain"]));
            }
            set {
                this["DownlinkReceiveGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkRange {
            get {
                return ((double)(this["DownlinkRange"]));
            }
            set {
                this["DownlinkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkPathLoss {
            get {
                return ((double)(this["DownlinkPathLoss"]));
            }
            set {
                this["DownlinkPathLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkGT {
            get {
                return ((double)(this["DownlinkGT"]));
            }
            set {
                this["DownlinkGT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkCN {
            get {
                return ((double)(this["DownlinkCN"]));
            }
            set {
                this["DownlinkCN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TotalCN {
            get {
                return ((double)(this["TotalCN"]));
            }
            set {
                this["TotalCN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UpOtherLoss {
            get {
                return ((double)(this["UpOtherLoss"]));
            }
            set {
                this["UpOtherLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkNoiseTemperature {
            get {
                return ((double)(this["DownlinkNoiseTemperature"]));
            }
            set {
                this["DownlinkNoiseTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkOtherLoss {
            get {
                return ((double)(this["DownlinkOtherLoss"]));
            }
            set {
                this["DownlinkOtherLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkCI {
            get {
                return ((double)(this["UplinkCI"]));
            }
            set {
                this["UplinkCI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteCI {
            get {
                return ((double)(this["SatelliteCI"]));
            }
            set {
                this["SatelliteCI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkCI {
            get {
                return ((double)(this["DownlinkCI"]));
            }
            set {
                this["DownlinkCI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ThresholdCNR {
            get {
                return ((double)(this["ThresholdCNR"]));
            }
            set {
                this["ThresholdCNR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MarginCNR {
            get {
                return ((double)(this["MarginCNR"]));
            }
            set {
                this["MarginCNR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteEIRP {
            get {
                return ((double)(this["SatelliteEIRP"]));
            }
            set {
                this["SatelliteEIRP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkNoiseBandwidth {
            get {
                return ((double)(this["DownlinkNoiseBandwidth"]));
            }
            set {
                this["DownlinkNoiseBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteHeight {
            get {
                return ((double)(this["SatelliteHeight"]));
            }
            set {
                this["SatelliteHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6378")]
        public double EarthRadius {
            get {
                return ((double)(this["EarthRadius"]));
            }
            set {
                this["EarthRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double AntennaElevation {
            get {
                return ((double)(this["AntennaElevation"]));
            }
            set {
                this["AntennaElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GeocentricAngle {
            get {
                return ((double)(this["GeocentricAngle"]));
            }
            set {
                this["GeocentricAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OrbitalPosition {
            get {
                return ((double)(this["OrbitalPosition"]));
            }
            set {
                this["OrbitalPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102.54")]
        public double DownGroundStationLongitude {
            get {
                return ((double)(this["DownGroundStationLongitude"]));
            }
            set {
                this["DownGroundStationLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30.05")]
        public double DownGroundStationLatitude {
            get {
                return ((double)(this["DownGroundStationLatitude"]));
            }
            set {
                this["DownGroundStationLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104.53")]
        public double UpGroundStationLongitude {
            get {
                return ((double)(this["UpGroundStationLongitude"]));
            }
            set {
                this["UpGroundStationLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31.26")]
        public double UpGroundStationLatitude {
            get {
                return ((double)(this["UpGroundStationLatitude"]));
            }
            set {
                this["UpGroundStationLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double UplinkBandwidth {
            get {
                return ((double)(this["UplinkBandwidth"]));
            }
            set {
                this["UplinkBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkEIRP2 {
            get {
                return ((double)(this["UplinkEIRP2"]));
            }
            set {
                this["UplinkEIRP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TransponderBandwidth {
            get {
                return ((double)(this["TransponderBandwidth"]));
            }
            set {
                this["TransponderBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UpCarrierFallback {
            get {
                return ((double)(this["UpCarrierFallback"]));
            }
            set {
                this["UpCarrierFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CarrierInputFallback {
            get {
                return ((double)(this["CarrierInputFallback"]));
            }
            set {
                this["CarrierInputFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UplinkEIRP3 {
            get {
                return ((double)(this["UplinkEIRP3"]));
            }
            set {
                this["UplinkEIRP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TransponderInputFallback {
            get {
                return ((double)(this["TransponderInputFallback"]));
            }
            set {
                this["TransponderInputFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteSFD {
            get {
                return ((double)(this["SatelliteSFD"]));
            }
            set {
                this["SatelliteSFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkEIRP {
            get {
                return ((double)(this["DownlinkEIRP"]));
            }
            set {
                this["DownlinkEIRP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TransponderOutputFallback {
            get {
                return ((double)(this["TransponderOutputFallback"]));
            }
            set {
                this["TransponderOutputFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CarrierOutputFallback {
            get {
                return ((double)(this["CarrierOutputFallback"]));
            }
            set {
                this["CarrierOutputFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkBandwidth {
            get {
                return ((double)(this["DownlinkBandwidth"]));
            }
            set {
                this["DownlinkBandwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteInPower {
            get {
                return ((double)(this["SatelliteInPower"]));
            }
            set {
                this["SatelliteInPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SatelliteGain {
            get {
                return ((double)(this["SatelliteGain"]));
            }
            set {
                this["SatelliteGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownCarrierFallback {
            get {
                return ((double)(this["DownCarrierFallback"]));
            }
            set {
                this["DownCarrierFallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UpTotalLoss {
            get {
                return ((double)(this["UpTotalLoss"]));
            }
            set {
                this["UpTotalLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DownlinkTotalLoss {
            get {
                return ((double)(this["DownlinkTotalLoss"]));
            }
            set {
                this["DownlinkTotalLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RollOff {
            get {
                return ((double)(this["RollOff"]));
            }
            set {
                this["RollOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SymbolRate {
            get {
                return ((double)(this["SymbolRate"]));
            }
            set {
                this["SymbolRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Rate {
            get {
                return ((double)(this["Rate"]));
            }
            set {
                this["Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ModulationOrder {
            get {
                return ((double)(this["ModulationOrder"]));
            }
            set {
                this["ModulationOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double InformationRate {
            get {
                return ((double)(this["InformationRate"]));
            }
            set {
                this["InformationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BitRate {
            get {
                return ((double)(this["BitRate"]));
            }
            set {
                this["BitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ThresholdEbN0 {
            get {
                return ((double)(this["ThresholdEbN0"]));
            }
            set {
                this["ThresholdEbN0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MarginEbN0 {
            get {
                return ((double)(this["MarginEbN0"]));
            }
            set {
                this["MarginEbN0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EbN0 {
            get {
                return ((double)(this["EbN0"]));
            }
            set {
                this["EbN0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Collapsed")]
        public string Show {
            get {
                return ((string)(this["Show"]));
            }
            set {
                this["Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RxAntennaNoiseTemperature {
            get {
                return ((double)(this["RxAntennaNoiseTemperature"]));
            }
            set {
                this["RxAntennaNoiseTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RxFeedlineLoss {
            get {
                return ((double)(this["RxFeedlineLoss"]));
            }
            set {
                this["RxFeedlineLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double NoiseFigure {
            get {
                return ((double)(this["NoiseFigure"]));
            }
            set {
                this["NoiseFigure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TxFeedlineLoss {
            get {
                return ((double)(this["TxFeedlineLoss"]));
            }
            set {
                this["TxFeedlineLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransponderSaturated {
            get {
                return ((string)(this["TransponderSaturated"]));
            }
            set {
                this["TransponderSaturated"] = value;
            }
        }
    }
}
